### ISSUE TITLE
Roadmap - Wishes, proposals and requirements 

### ISSUE THREAD

**Issue by isublimity** [tabixio/tabix#12]
I suggest here to express all wishes and proposals - maybe they will be implemented in the near future

Предлагаю тут высказать все пожелания и хотелки - возможно они будут реализованы в ближайшее время

**Comment by isublimity** [comment]
Current roadmap tabix.UI:


- Reduce the memory leak and CPU consumption
- Assistant to create graphs
- If there is an error in the request - position the cursor on the error
- Support where local in - the ability to attach a file to a query
- Display the status of the query execution

Current roadmap tabix.proxy:

- Connection to MySQL and REST services - routing of requests and support of several databases
- Sharing queries and results - you can send a link to a friend with a query and result, without access to the database itself
- LDAP authorization allows you to exclude direct access to CH / MySQL
- Building a dashboard

---


Текущий roadmap tabix.UI: 


- Снизить утечку памяти и потребления CPU
- Помошник создания графиков 
- При ошибки в запросе - позиционировать курсор на ошибку
- Поддержка where local in - возможность аттачить файл к запросу
- Отображать статус выполнение запроса 

Текущий roadmap tabix.proxy:

- Подключение к MySQL и REST сервисам - маршрутизация запросов и поддержка нескольких баз данных
- Шаринг запросов и результатов - можно отправить ссылку другу с запросом и результатом, без доступа к самой БД 
- LDAP авторизация  позволяет исключить прямой доступ к CH/MySQL
- Построение dashboard

**Comment by vas-and-tor** [comment]
Please, add an option to enable/disable tabs switching by ctrl+left-right.
Default behavior (go to next-previous word) is very useful to navigate through code, and I miss it too much :smile:

**Comment by proller** [comment]
Add values from system.events to /#/metrics .
(Note: events with values=0 not shown in table )

**Comment by umaxfun** [comment]
Mac hotkeys for tabs are also strange. Cmd+Left-Right usually work as Home-End in code editors, and in Tabix they switch tabs, with animations and everything.

**Comment by isublimity** [comment]
new release 
fix keys
fix metrics

**Comment by isublimity** [comment]
`
From chat: 
`
Привет. Отличный вроде UI и время от времени использую но постоянно замечаю что скатываюсь в CLI. Даже когда запросы большие, все равно пишу их в какой нибудь десктопной IDE (idea, sublime) и потом вставляю в CLI.  
0. Сделать персистентные проекты не в JS сессии, а в самом кликхаусе. Есть же отличное место для хранения, чего бы не использовать :) При сохранении проекта указывать базу и префикс таблиц. Там хранить все настройки, табы, логи, сохраненные запросы и графики. Что бы из любого места можно было получить тот же проект в том же самом месте где его оставил на другом браузере. 
1. Задержка которая там после того как уже кликнул мышкой на место в запросе и до того как уже можно начинать писать текст - очень некомфортная. Даже после отключения автокомплита. Если можно сделать быструю смену между простым режимом, без задержки, и красивым режимом с тормозами, но автокомплитом, подсветкой, строками и форматированием - было бы круто. После 500го запроса автокомплит уже не нужен, а задержка все еще мешает :) Задержка, мигание экрана и анимация между переходами по табам тоже раздражает, но я не знаю если это лечится.
2. В CLI можно несколько раз кликнуть вверх и получить запрос который был 3 запуска назад - используется постоянно. В табикс есть "query log", и есть request's log - но они оба странные и не решают задачу полностью. request log не по табу, а вообще по всей системе, а "query log" - я так и не понял как пользоваться. Ну и конечно доступ в 2 и более кликов мышкой - это совсем не так эффективно как из CLI
3. Логичное продолжение аналитической части - сохранять запросы с их выбранной визуализацией (таблица, график) отдельно с возможностью расшарить.
3.0 Добавить возможность обьединять их в дашбоарды. Query -> SavedSlice, Slices -> Dashboard 
3.1. Сохранять последний набор данных для Slice, так что бы при открытии график сразу показывался. Таким образом ссылка на дашбоард будет открываться всегда с красивыми графиками. Перезапуск требуется далеко не во всех случаях и может быть совсем не часто.
3.2 Для запросов ввести параметризацию с дефолтами. Так что бы из редактора выполнянлись дефолтные значения, а из slice или dashboard эти значения переписывались текущими для дашбоарда. В итоге получатся интерактивные дашбоарды когда меняя параметр можно будет обновить сразу весь дашбоард. И для расшаренных slice пользователь без возможности (или способности) редактировать код сможет поиграть с параметрами.

Независимо от того будут эти хотелки реализованы или нет, спасибо за работу! По ощущениям - получается отличный продукт.

**Comment by isublimity** [comment]
>>> 💎, [Nov 6, 2017, 8:47:12 PM]:
Было бы удобно, если бы запросы сохранять ввиде одной кнопки сбоку в списке...с наименованием. Как правило аналитики часто выполняют один и тот же отчет. А sql редактор можно вообще скрывать при таком использовании ui. Знаю...пахнет немного фейсбуком...но чем мы хуже...да еще и бесплатно

И если бы можно было поля использовать в качестве измерений...что то типа как в микростратежи или том же фейсбуке. То есть без куба, но со срезом получаемым сохраненным/готовым запросом...ну или что то типа этого. Все бы просто писились от этого инструмента


analytics.facebook.com

**Comment by Tasselmi** [comment]
functionality to disable  data download or control maxSize of data-downloaded.
we have data-safe problems.

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
