### ISSUE TITLE
Add possibility to connect to internal clickhouse address

### ISSUE THREAD

**Issue by plutov** [tabixio/tabix#170]
Currently it connects to public ClickHouse by providing a URL.

We don't want to expose ClickHouse and tried to set `CH_HOST` but it still does a request from browser.

It would be nice that Tabix backend can do a request from server, where the server has access to CH.

**Comment by digitalist** [comment]
you can hide Tabix behind nginx+https+auth and proxy clickhouse requests to internal network

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
