### ISSUE TITLE
No SSH. Is Tabix working?

### ISSUE THREAD

**Issue by Bromanskiy** [tabixio/tabix#184]
@isublimity 
Игорь, привет.
Подскажи, пожалуйста, когда планируется новый релиз табикса? Очень классная тула. Хочется продолжать ей пользоваться, однако как минимум беспокоит отсутствие SSH-сертификата.
Спасибо!

**Comment by KIRILLxBREAK** [comment]
Такой же вопрос. Можно ли в Tabix подключаться к clickhouse через ssh-tunnel?

**Comment by isublimity** [comment]
Из http://ui.tabix.io и из http://aplha.tabix.io можно подключиться к Clickhouse за SSL сертификатом. 

Но, нужно чтобы ваш браузер доверял этому сертификату ( за которым спрятан Clickhouse )

Как это можно проверить: 
Открываем в браузере : httpS://111.22.33.44:8123/?user=XXX&password=YYY  если clickhouse ответит OK и браузер не будет ругаться на ваш сертификат -> Tabix сможет подключится. 

Из за политики безоп. браузеров CORS, невозможно с https сайтов подключатся к НЕ httpS.
Если я уберу ui.tabix.io за SSL то не будет возможности подключится к обычному ch . ;( 
Возможно в ближайшее время я опубликую alpha версию за SSL. 

Отпишусь тут

**Comment by isublimity** [comment]
Сами сайты http://ui.tabix.io и http://aplha.tabix.io не владеют вашей информацией, и к ним ни как не поступают ваши пароли и ваши запросы. 

Это только загрузчики JS кода, для самой оболочки.

**Comment by thinOptimist** [comment]
Есть ли возможность подключиться без связки логин-пароль через pem-сертификат?

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
