### ISSUE TITLE
Module 'ui.router' is not available!

### ISSUE THREAD

**Issue by lyc0221** [tabixio/tabix#195]
![image](https://user-images.githubusercontent.com/40416749/53321207-b592c480-3912-11e9-9f97-72a8714090d0.png)

node: 6.7.0

https://tabix.io/doc/Develop/

Why does it prompt the above error after I gulp build ?

**Comment by isublimity** [comment]
Current master version - not supporting ( 

You can see new version Tabix in branch alpha: 

https://github.com/tabixio/tabix/tree/ts

http://alpha.tabix.io/

**Comment by lyc0221** [comment]
thanks, resolved if I use  branch` ts`

**Comment by Mumusen** [comment]
> ![image](https://user-images.githubusercontent.com/40416749/53321207-b592c480-3912-11e9-9f97-72a8714090d0.png)
> 
> node: 6.7.0
> 
> https://tabix.io/doc/Develop/
> 
> Why does it prompt the above error after I gulp build ?

请问项目代码还在吗？遇到类似的问题，请教下

**Comment by lyc0221** [comment]
use branch ts
