### ISSUE TITLE
Code: 113, e.displayText() = DB::Exception: There is no session

### ISSUE THREAD

**Issue by kindred77** [tabixio/tabix#197]
Get error when I execute set distributed_product_mode ='local'.

**Comment by vladignatyev** [comment]
@kindred77 this error is a Clickhouse's thing. In short, Clickhouse is not configured to use sessions. Not sure if sessions are supported for HTTP clients at all. (Tabix is HTTP client).

**Comment by kindred77** [comment]
I get it, thanks
