### ISSUE TITLE
Always error on login

### ISSUE THREAD

**Issue by yong2khoo88** [tabixio/tabix#200]
"Login or connect error...."

![image](https://user-images.githubusercontent.com/5007089/57822211-eb36a380-77c5-11e9-948d-7e970267ad20.png)

Tried:
1. http://192.168.0.167:1433
2. set port 1433 in SQL configuration
3. localhost:1433
4. myComputerName:1433
5. connect to a remote azure sql

all fails... >.<
What did i miss

**Comment by sergeydi** [comment]
I have the same issue. Do you found how to solve it?

**Comment by sergeydi** [comment]
In my case it happens because chrome blocked JS from my server.

**Comment by volkovartem77** [comment]
Make sure that you uncomment the line: 
`<http_server_default_response><![CDATA[<html` ng-app="SMI2"><head><base href="http://ui.tabix.io/"></head><body><div ui-view="" class="content-ui"></div><script src="http://loader.tabix.io/master.js"></script></body></html>]]></http_server_default_response>` in config file /etc/clickhouse-server/config.xml. 
In my case, this line affected on login Tabix.

**Comment by Fanduzi** [comment]
same issue..

**Comment by usatenko** [comment]
is it somehow possible to have httpS://loader.tabix.io/master.js instead http to be able to load it from https hosts, instead browser blocks them

**Comment by geekyouth** [comment]
https://github.com/tabixio/tabix/issues/210#issuecomment-633440155

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
