### ISSUE TITLE
support https://www.npmjs.com/package/d3-flame-graph for flamegraph rendering

### ISSUE THREAD

**Issue by Slach** [tabixio/tabix#204]
How easy integrate https://www.npmjs.com/package/d3-flame-graph into app/draw ?
it will be really cool to analyze system.trace_log with query like this 
https://gist.github.com/alexey-milovidov/92758583dd41c24c360fdb8d6a4da194

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
