### ISSUE TITLE
Issues with connecting to the ClickHouse

### ISSUE THREAD

**Issue by Arhimag** [tabixio/tabix#210]
Hello!
Thank you very much for your software! Can you help me, how can I check, what kind of issues have my tablix installation, when it is connecting to my clickhouse server. 

When I'm checking URL of clickhouse manually I obtained "ok" page. But in tablix i get this error:
![image](https://user-images.githubusercontent.com/4159523/72219915-4f2f8880-355c-11ea-941a-27cd02947e46.png)

I received this message simultaneously, after hitting the button "sign in"

Thank you!

**Comment by sunny19930321** [comment]
the same of question

**Comment by IdahoPL** [comment]
If you connect to Tabbix using https then make sure you connect to to Clickhouse with https://<ip|domain>:<https port, 8443 by default>

If you want to connect to Clickhouse with http://<ip|domain>:<http port, 8123 by default> than you have to connect to Tabbix using http, not https.

**Comment by alfonsodg** [comment]
I have the same problem, using the cli from another host i can access however using the web ui gives me the same error: user/password error, i am using the "default" user with no password, i need a password for that user?

**Comment by winter7** [comment]
Is this issue resolved and what does ClickHouse need to configure with it

**Comment by Fanduzi** [comment]
same issue, we use cloud, so we deploy tabix on ecs by docker, we connect tabix use https. why connect to tabbix use https must connect clickhouse use https?

**Comment by Fanduzi** [comment]
> the same of question

你好,这个问题你解决了吗. 是说通过https访问tabix就必须访问ch的https_port吗? 但是我试了也不行

**Comment by geekyouth** [comment]
![image](https://user-images.githubusercontent.com/12899262/82791984-4010fd80-9ea1-11ea-8aba-c7f08b54462a.png)

![image](https://user-images.githubusercontent.com/12899262/82792092-69318e00-9ea1-11ea-990f-3380fb6a331a.png)

我是自己部署的，但是好像需要依赖境外 cdn 之类的静态文件，如果开了代理，打开网页就比较快，否则要开很久。

**Comment by wang2222qq** [comment]
如果遇到需要跳板机才能CK的情况，怎么解决？

**Comment by huoarter** [comment]
> ![image](https://user-images.githubusercontent.com/12899262/82791984-4010fd80-9ea1-11ea-8aba-c7f08b54462a.png)
> 
> ![image](https://user-images.githubusercontent.com/12899262/82792092-69318e00-9ea1-11ea-990f-3380fb6a331a.png)
> 
> 我是自己部署的，但是好像需要依赖境外 cdn 之类的静态文件，如果开了代理，打开网页就比较快，否则要开很久。

good!

**Comment by huoarter** [comment]
> > the same of question
> 
> 你好,这个问题你解决了吗. 是说通过https访问tabix就必须访问ch的https_port吗? 但是我试了也不行

我用尝试使用https解决了，大概原因是：
1、使用https需要证书，签证书需要对应域名
2、连接https，请使用域名,不能使用ip

**Comment by zeronobody** [comment]
the same of question too

**Comment by xinxinfly** [comment]
> 如果遇到需要跳板机才能CK的情况，怎么解决？

t同问

**Comment by ShellongC** [comment]
While I connect to the clickhouse,I get the same error, and while i open the console,i find the real reason is "CORS error",mainly because the tabix server and clickhouse server are on the different host.
tabix address: http://beta.tabix.io/#!/login
clickhouse server: localhost:8321.
So do I need extra configuration work?

**Comment by Craillon** [comment]
I had same problem but i found the solution, go to this : [https://tabix.io/doc/Server/Config/](url)

**Comment by Craillon** [comment]
use:
http://127.0.0.1:8123
login: tabix2
password : tabix2

and check Http Base Auth.

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.

**Comment by zeronobody** [comment]
你好，也许我不能及时阅读你的邮件，请谅解，我会尽快查看邮件的。请你耐心等待。谢谢！
