### ISSUE TITLE
🚫Requirements Chrome!🚫

### ISSUE THREAD

**Issue by alex-mayorga** [tabixio/tabix#213]
¡Hola!

Could you please let me know why this warning is shown in Firefox?

![image](https://user-images.githubusercontent.com/649262/81852912-6047d080-9521-11ea-9f42-7b1bcab9268c.png)

Most of the functionality seems to work regardless.

What am I missing by sticking up with Firefox?

¡Gracias!
Alex

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
