### ISSUE TITLE
Is Tabix no longer actively maintained?

### ISSUE THREAD

**Issue by djrobby** [tabixio/tabix#222]
Question as per the title. If yes, please update the repo README with this info. Thank you!

**Comment by ddon** [comment]
May be offer some alternatives? May be it was forked and somebody fixing all the bugs there?

**Comment by Miantang** [comment]
try sqlpad/sqlpad

**Comment by isublimity** [comment]
Tabix in "reload", new release planed in this month
Work in brach ts21
https://github.com/tabixio/tabix/tree/ts21

**Comment by ddon** [comment]
Yes!!!!! Finally! :)

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
