### ISSUE TITLE
Can`t connect to clickhouse with tabix after update to ch version 21.4.4.30

### ISSUE THREAD

**Issue by AlexanderDobrokhodov** [tabixio/tabix#224]
Can`t connect to direct ch with tabix after update to version 21.4.4.30 with error
Code: 47, e.displayText() = DB::Exception: Missing columns: 'key' while processing query: 'SELECT name, key, attribute.names, attribute.types FROM system.dictionaries ARRAY JOIN attribute ORDER BY name ASC, attribute.names ASC', required columns: 'name' 'key', maybe you meant: ['name'], arrayJoin columns: 'attribute.names' 'attribute.types' (version 21.4.4.30 (official build))
system.dictionaries have been modified at version 21.4.4.30
https://github.com/ClickHouse/ClickHouse/commit/a53c90e509d0ab9596e73747f085cf0191284311?branch=a53c90e509d0ab9596e73747f085cf0191284311&diff=unified

**Comment by tomjackone** [comment]
same here.
any alternatives?

**Comment by tomjackone** [comment]
line 170 of src/app/services/api.js:
/ @todo - need rewrite async / await
            // тут нужно или остановить другие потоки, и повесить ожидание пока не завершиться инициализация
            // Глобавльно без и
            console.time("Load Database Structure!");
            this.fetchQuery( "SELECT * FROM system.columns" ).then(columns => {
                this.fetchQuery( "SELECT database,name,engine FROM system.tables" ).then(tables => {
                    this.fetchQuery( "SELECT name FROM system.databases" ).then(databases => {
                        this.fetchQuery("SELECT name,**_key_**,attribute.names,attribute.types from system.dictionaries ARRAY JOIN attribute ORDER BY name,attribute.names", null).then((dictionaries) => {
                            this.fetchQuery("SELECT name,is_aggregate from system.functions", null).then((functions) => {
                                console.timeEnd("Load Database Structure!");
                                this.DS_storeCache(columns.data,tables.data,databases.data,dictionaries.data,functions.data);
                                _DatabaseStructure.init(columns.data,tables.data,databases.data,dictionaries.data,functions.data);
                                return call(_DatabaseStructure);
                            } , (response) => {throw response } );//functions
                        } , (response) => {throw response } );//dictionaries
                    } , (response) => {throw response } );//databases
                } , (response) => {throw response } );//system.tables

            } , (response) => {throw response } );//system.columns

            return ;

        };

**Comment by Fahrenheit35** [comment]
Hello to everyone!
Today I can fix this bug by updating the files:
/build/scripts/app-65ac869b2e.js
/build/scripts/app.js
I replaced the "key" by "key.names" and "key.types" in line in both files:
![image](https://user-images.githubusercontent.com/22673545/115669689-36ae4080-a351-11eb-9583-31487450cc2e.png)
 and everything work!

**Comment by AlexanderDobrokhodov** [comment]
Hello @Fahrenheit35 
Can you post a modified version for public access?

**Comment by wq2455175746** [comment]
docker run mode 
/var/www/html/scripts/app-59ab3f78f6.js
/var/www/html/scripts/app.js
you can  replace the "key" by "key.names" and "key.types" in line in both files:
then
docker run --rm -d  --network=host  --name ck_tabix -v /ssd1/services/tabix/app-59ab3f78f6.js:/var/www/html/scripts/app-59ab3f78f6.js -v /ssd1/services/tabix/app.js:/var/www/html/scripts/app.js   spoonest/clickhouse-tabix-web-client

**Comment by AlexanderDobrokhodov** [comment]
I use tabix locally. After replace "key" by "key.names" and "key.types" in line in both files it still didn`t work. How i can rebuild it?

**Comment by oxydaemon** [comment]
If you use it locally and don't want to rebuild you can directly change the files in build/scripts (the two js app files) as per @Fahrenheit35 fix above

**Comment by alex-kabin** [comment]
you can use fixed version in my docker image: alexkabin/clickhouse-tabix-web-client:18.07.1a

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
