### ISSUE TITLE
Не могу подключиться к clickhouse

### ISSUE THREAD

**Issue by pilatius87** [tabixio/tabix#226]
Просьба помочь разобраться, что я делаю не так.
Мне предоставили доступ к clickhouse.
Решил работать с ним через tabix
Открываю http://ui.tabix.io/#!/login
Ввожу данные, но получаю "Login or connect error, check host:port,login & password".
Обновляю страницу и почему то оказываюсь авторизованным и идет загрузка БД, но потом вылетает ошибка.
Используя абсолютно такие же данные, мой коллега успешно коннектится.
В чем может быть проблема?
![Screenshot_3](https://user-images.githubusercontent.com/61042770/119255467-5611e500-bbff-11eb-8535-577c8f902419.png)

**Comment by baddeiv** [comment]
Привет! Получилось разобраться? Я столкнулся с такой же проблемой.

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
