### ISSUE TITLE
Potential Security Issues

### ISSUE THREAD

**Issue by JamieSlome** [tabixio/tabix#227]
Hello @isublimity - we received disclosures for a potential vulnerability against your repository from @hakkk3r.

I couldn't find a security policy on your repository, or a contactable e-mail to get in touch with you.

You can take a look at the advisories [here](https://huntr.dev/bounties/1-other-tabixio/tabix/) and [here](https://huntr.dev/bounties/2-other-tabixio/tabix/) - it is protected and only you and the reporter can see the information.

If you would prefer to receive the disclosure information via e-mail or would like me to post the details on this issue instead, let me know and I will follow up with you.

-- Jamie 🍰

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
