### ISSUE TITLE
Connection problem when using tabix

### ISSUE THREAD

**Issue by chasingegg** [tabixio/tabix#229]
![image](https://user-images.githubusercontent.com/18375889/129391805-587fcaad-9650-4fd5-b969-d2811ef992ce.png)
when I try to use tabix, it seems the connection is established, but this web page is never change, only the `login ok!loading...` disappear, nothing has changed, what is the problem ?

**Comment by malcolm061990** [comment]
I can't even connect to my working CH cluster - ClickHouse 20.8.18.32.
It shows "login or connect error". But in my env there is no login and password, I just use hostname

**Comment by ShellongC** [comment]
I get the CORS error.
The official document is so short. Is there any speicl configuration for the users before using Tabix?

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
