### ISSUE TITLE
how can i transfer all database in PostgreSQL to clickhouse with tabix

### ISSUE THREAD

**Issue by zkuser2002** [tabixio/tabix#234]
I want to change database from postgresql to clickhouse 
At first I should transfer data from postgresql to clickhouse.  Then i use the code 
Create database...... 
It is ok , but when i run the code some time i see the tables also come to clickhouse space and some times just transfer only database. 
So as I ask you I should create table for transfer tables of database, 
But when I try on it, I got an error that this table are exist,  but I dont see it in clickhouse.  
I need the code that I can transfer data from postgresql to clickhouse and also for create table

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
