### ISSUE TITLE
Missing header in latest version?

### ISSUE THREAD

**Issue by wangqinghuan** [tabixio/tabix#238]
I have updated latest code and install it. This is what I see.
![image](https://user-images.githubusercontent.com/22762150/166869242-7c010349-a933-46cd-a967-9e6e76230405.png)
Is the header missing?
![image](https://user-images.githubusercontent.com/22762150/166869389-ffe96c19-4b01-409f-97ff-0765e0538cc7.png)

**Comment by wangqinghuan** [comment]
right click on database.
![image](https://user-images.githubusercontent.com/22762150/166885974-995901a0-1b8c-4185-ad9d-3280023587d7.png)

**Comment by isublimity** [comment]
Version in master not quite ready for production use
