### ISSUE TITLE
Code: 352. DB::Exception: Block structure mismatch (AMBIGUOUS_COLUMN_NAME) 

### ISSUE THREAD

**Issue by digipigeon** [tabixio/tabix#242]
I have just upgraded my main clickhouse server

Running Ubuntu `22.04`

ClickHouse server version `22.4.5.9` (official build). - Installed from Repo

Using the Hosted UI.

When looking at the processlist I am getting the following error, (everything else appears to be working correctly):

```
Code: 352. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
memory_usage String String(size = 0)
memory_usage Int64 Int64(size = 0). (AMBIGUOUS_COLUMN_NAME) (version 22.4.5.9 (official build))
```

**Comment by isublimity** [comment]
You use last version hosted on http://dash.tabix.io ?

**Comment by digipigeon** [comment]
I was using (what I now know is the older) ui.tabix.io

Everything is working fine on this new one, thanks.
