### ISSUE TITLE
Unable to connect to clickhouse

### ISSUE THREAD

**Issue by shubham696** [tabixio/tabix#248]
Trying to connect with [automatic CH](https://tabix.io/doc/Install/#variant-5-from-docker) connection but, getting timeout or getting error  **Error on load database structure**

**Comment by isublimity** [comment]
Version tabix ?
Version CH ?

**Comment by shubham696** [comment]
@isublimity  
I'm using the latest for both tabix and CH(i.e. clickhouse/clickhouse-server)
