### ISSUE TITLE
Does anyone know why http://ui.tabix.io/ is not accessible？

### ISSUE THREAD

**Issue by Tiakon** [tabixio/tabix#263]
I used an embedded Tabix link ​in clickhouse as a visual interface for editing sql. Now it is inaccessible. I wonder what happened to it and whether it will recover？

**Comment by carlgrundberg** [comment]
Same problem here, haven't found any information.  I use this for now: http://www.clickcat.cloud/

There is a comprehensive list of alternatives here: https://clickhouse.com/docs/en/interfaces/third-party/gui

**Comment by Tiakon** [comment]
Thank you for your advice. I am aware of these things. I am simply curious about what happened to tabix and if it will recover.

**Comment by Tiakon** [comment]
> Same problem here, haven't found any information. I use this for now: http://www.clickcat.cloud/
> 
> There is a comprehensive list of alternatives here: https://clickhouse.com/docs/en/interfaces/third-party/gui

Thank you for your advice. I am aware of these things. I am simply curious about what happened to tabix and if it will recover.

**Comment by isublimity** [comment]
#262 

lost server, my provider drop data, and kill server

**Comment by javohirss** [comment]
> #262
> 
> lost server, my provider drop data, and kill server
When will it be available again? I mean do you restore it?
