### ISSUE TITLE
TABIX.SERVER problem

### ISSUE THREAD

**Issue by Foxsa** [tabixio/tabix#3]
tabix Build 17.03.3
CH 1.1.54189

При попытке подключится к CH через TABIX.SERVER
Ошибка доступа.
Через DIRECT CH все ок.

Подробно: 
Он шлет в clickhouse запрос 
OPTIONS /query HTTP/1.1

на что тот отвечает 
HTTP/1.1 501 Not Implemented

С чем это может быть свзяано?

**Comment by isublimity** [comment]
используйте режим direct, tabix.server это пока закрытая разработка - выступающая в роли прокси перед CH

**Comment by Foxsa** [comment]
Спасибо, моя задача именно включала в себя прокси

**Comment by dragonsmith** [comment]
@isublimity Игорь, а подскажите, пожалуйста, в каком состоянии сейчас Tabix.Server? Т.к. не нахожу никакой документации, то поднимаю эту issue. Все еще закрытая разработка? Было бы очень круто как-то выложить tabix.ui в интернет, не выкладывая туда доступа к clickhouse.

P.S. Коллеги пользуются Tabix, им нравится. Так что передам "Спасибо" вместо них.

**Comment by isublimity** [comment]
Мое свободное время занял перезд в новое место)

В ближайшие пару недель надеюсь доделать alpha, так сказать на посмотреть )
