### ISSUE TITLE
Use Basic Authentication Instead of Query Params

### ISSUE THREAD

**Issue by elithrar** [tabixio/tabix#38]
RE: https://github.com/smi2/tabix.ui/blob/e238181b55039597ad7cee2e44c8322b59060ff6/src/app/services/api.js#L173-L178

The current code appends the username & password as URL query params, which puts the plaintext password at (high) risk of being logged in web-server logs.

* The [Clickhouse HTTP interface](https://clickhouse.yandex/docs/en/interfaces/http_interface.html) supports HTTP Basic Authentication, and thus we should use this instead.
* This does mean that the server/proxies will need to return an "Access-Control-Allow-Origin" header, as adding an Authorization header (or any other header) no longer allows the requests to be simple requests, and thus browsers enforce CORS policies.

I'm looking at modifying Tabix to work in two ways:

* In the case where a username + password are supplied, use Basic Auth
* If only a username is supplied (no password), use query params

**Comment by isublimity** [comment]
Try beta branch 
https://github.com/smi2/tabix.ui/blob/beta/src/app/services/api.js#L346

I can`t test work - I do not have authentication due to CORS headers (

**Comment by elithrar** [comment]
@isublimity Would you be opposed to making Basic Auth the default mode, and changing the checkbox to say "Use Query Params (insecure)" instead? I am happy to update my PR if that makes sense.

Better to guide users to the safer method of authentication where possible.

**Comment by elithrar** [comment]
e.g.

<img width="500" alt="screen shot 2017-09-29 at 4 03 57 am" src="https://user-images.githubusercontent.com/18544/31013526-5d8adf70-a4cb-11e7-824c-7939ce1868b2.png">

**Comment by elithrar** [comment]
Branch I can push that implements the above: https://github.com/elithrar/tabix.ui/tree/msilverlock/basic-auth-default

**Comment by isublimity** [comment]
I have a http CORS error when "basic-auth"  - I'm afraid that other users will not work either

**Comment by elithrar** [comment]
* Yes, if you're not using a proxy, ClickHouse will return an error as the OPTIONS request made by the browser will NOT (by design, for security) include your credentials, until the server responds with an `Access-Control-Allow-Origin` and `Access-Control-Allow-Credentials` response headers.
* Thus, we would still support the Auth via URL params method (checkbox) to allow users to opt-in to non-CORS behaviour, with the risk of having their credentials logged by (nearly all) web-servers that log the URL.
* By default, Direct Connect mode should prefer the safer Basic Authentication method, to prevent leaking credentials to web-server logs.
* I can update the documentation to also clarify this.

Let me know if you're still interested in the PR to improve the default security mode.

**Comment by elithrar** [comment]
To be clear: we still keep the "simple" option, but because of its insecurity we don't make it the default. That way you can check the box and still log-in without issue @isublimity :)

<img width="609" alt="screen shot 2017-09-29 at 4 03 57 am" src="https://user-images.githubusercontent.com/18544/31020612-560f20cc-a4e8-11e7-8532-3f4d02e1ea7e.png">

**Comment by valyala** [comment]
Try [chproxy](https://github.com/Vertamedia/chproxy). It supports `readonly=1` users and `https` out of of the box. Additionally we'll be glad to fix quickly any `CORS`-related issues. See also #41 .

**Comment by isublimity** [comment]
add in master
