### ISSUE TITLE
CREATE TABLE ... AS SELECT uses "Max result rows" as if it was doing a SELECT

### ISSUE THREAD

**Issue by piotrp** [tabixio/tabix#50]
When I issue `CREATE TABLE ... AS SELECT ...` query and SELECT returns more rows than `Max result rows` configured in Tabix settings the query gets aborted with `Code: 158, e.displayText() = DB::Exception: Limit for result rows exceeded: read 1003137 rows, maximum: 1000000, e.what() = DB::Exception` error.

IMHO in case of CREATE... queries max_query_rows parameter should be skipped, or it should be set separately for DDL and for queries.

**Comment by isublimity** [comment]
In Clickhouse release 1.1.54356, 2018-03-06
* Limits and quotas on the result are no longer applied to intermediate data for INSERT SELECT queries or for SELECT subqueries.

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
