### ISSUE TITLE
the tabix can't show table STRUCTURE and table data By the sidebar

### ISSUE THREAD

**Issue by naah69** [tabixio/tabix#51]
i am newcomer to clickhouse.
i install  1.1.54236  clickhouse on my linux computer.
i use http://ui.tabix.io to connect my clickhouse.
it can query SQL , but can't show table structure and table data by the sidebar.
excuse me, can u tell me where is wrong?

**Comment by isublimity** [comment]
Open browser console -> see error messages for more information

**Comment by naah69** [comment]
![Uploading 未命名图片.png…]()
it seems  not to commit SQL

**Comment by naah69** [comment]
SQL> http://192.168.79.124:8123/?add_http_cors_header=1&log_queries=1&output_format_json_quote_64bit_integers=1 SHOW CREATE TABLE log.aliasDemo

 FoRmAt JSON

**Comment by naah69** [comment]
"http://192.168.79.124:8123/?add_http_cors_header=1&log_queries=1&output_format_json_quote_64bit_integers=1"

**Comment by naah69** [comment]
Request URL:http://192.168.79.124:8123/?add_http_cors_header=1&log_queries=1&output_format_json_quote_64bit_integers=1
Referrer Policy:no-referrer-when-downgrade
Request Headers
Provisional headers are shown
Access-Control-Request-Headers:authorization
Access-Control-Request-Method:POST
Origin:http://ui.tabix.io
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Query String Parameters
view source
view URL encoded
add_http_cors_header:1
log_queries:1
output_format_json_quote_64bit_integers:1

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
