### ISSUE TITLE
Sign in error in tabix with my company IP

### ISSUE THREAD

**Issue by sachinkademane** [tabixio/tabix#52]
Hi all,
I was trying to see data from clickhouse on tabix, so i opened tabix ui on browser and started entering credentials but it is asking me to check my ip,port.user name and password
![image](https://user-images.githubusercontent.com/27882431/34706213-180d9bd4-f52c-11e7-9cf5-e95363a144e4.png)
and also if i do below command on my console it says ok....what might be the problem?
```
[root@AELAB110 ~]# curl 'http://localhost:8123/'
Ok.
```

**Comment by isublimity** [comment]
Try disable HTTP Base auth

**Comment by tallanvor** [comment]
Hi. Have same issue.
Clean setup of clickhouse, clean nginx + last tabix release

- I'm tried to connect from server in same network - no effect
- Tried to connect from localhost - no effect
- Tried to setup password for user "default" - no effect

Curl told - "Ok." from everywhere....

**Comment by isublimity** [comment]
Check  in new build 18.04.1

**Comment by avi0gaur** [comment]
I am facing same issue using docker to install tabixui.
- Changed password of default user in clickhouse server
-using "default" as user name

**Comment by volkovartem77** [comment]
Make sure that you uncomment the line
<http_server_default_response><![CDATA[<html ng-app="SMI2"><head><base href="http://ui.tabix.io/"></head><body><div ui-view="" class="content-ui"></div><script src="http://loader.tabix.io/master.js"></script></body></html>]]></http_server_default_response> in config file /etc/clickhouse-server/config.xml.
In my case, this line affected on login Tabix.

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
