### ISSUE TITLE
Инициализация таблицы с колонкой Array(UInt64)

### ISSUE THREAD

**Issue by ru7701** [tabixio/tabix#55]
Найдено непонятное поведение в одном наверное редком случае.
Если создать ReplacingMergeTree таблицу с колонкой Array(UInt64) и вставить первые две строки с пустыми значениями в ней

> `CREATE TABLE test64 ( date Date, vers UInt64, attribute Array(UInt64) ) ENGINE = ReplacingMergeTree( date, ( vers ), 8192, vers)`
> `INSERT INTO test64 (vers,attribute) VALUES (1,[]),(2,[])`

...то таблица перестает отображаться в TABiX. 
Т.е., например, на запрос

> `select * from test64`

ответ не приходит и только переливается полоска процесса (".... select * from test64"). Этот же запрос в linux-клиенте отрабатывает нормально. В логах КХ ошибки не возникают.

При этом, если же хотя бы в одной из первых двух записей значение указать (включая значение 0), или поменять тип данных на, допустим, Array(UInt32), то все Ок.

Версия КХ 1.1.54343, но тоже самое было на ранних.

**Comment by isublimity** [comment]
пофиксю скоро, спасибо за баг) их два) 
Если запрос НЕ select :   
` Uncaught (in promise) TypeError: Cannot set property 'prepareInt64Cols' of null`

Если select test64 

`Uncaught (in promise) TypeError: Cannot read property 'attribute' of undefined
В  коде  n=parseInt(_.maxBy(e.data,function(e){return _.isEmpty(e[a.name])?void 0:parseInt(e[a.name])})[a.n
`

**Comment by ru7701** [comment]
Я, по большей части, гуманитарий. Поэтому ничего особо из приведенных цитат не понял)
Правда, вот жизнь заставила кодить и даже писать специфическую OLTP-СУБД на perl-e. И там, в этой БД, один из 8-ми базовых типов имеет атрибут Array(UInt64). При этом, база фоном откидывает данные в КХ, который мониторится через Ваш шикарный TABiX. ...Вот так на ошибку и вышел.  
Что бы не терять доступа к TABiX пришлось даже ужать айди до UInt32. Ну, правда, когда понял в чем дело стал просто ставить Array([0]) при пустоте в атрибуте. Так что вопрос и не критичный, но все равно спасибо за мейнтейнерство!

**Comment by isublimity** [comment]
Это я для себя писал -- где искать ошибку) 

Спасибо за баг -- поправил
