### ISSUE TITLE
Статус

### ISSUE THREAD

**Issue by k0st1an** [tabixio/tabix#59]
Проект живой?

**Comment by isublimity** [comment]
Даже очень)

**Comment by k0st1an** [comment]
UI наверное да :) Что на счет сервера?

**Comment by isublimity** [comment]
Планы 
- Полностью изменить UI часть, переписать на другом Framework
- После первых релизов новой UI делать под него Server 

Новый UI нужен т/к подержка текущего проблематична

**Comment by k0st1an** [comment]
Ясно. Спасибо.
