### ISSUE TITLE
Значение в в ответе меняется при копировании

### ISSUE THREAD

**Issue by Gring0** [tabixio/tabix#60]
Добрый вечер!

Значение в гриде с ответом меняется при копировании:
1) Вот сразу после выполнения селекта https://yadi.sk/i/oHTQw4XT3TyWaA
2) Попытался скопировать, значение поменялось на 3107276162941849000 https://yadi.sk/i/tliojJxo3TyWY8

Значение типа UInt64
Хром Версия 65.0.3325.181

**Comment by isublimity** [comment]
Поправил в 18.04.1, проверьте 
https://tabix.io/doc/Changelog/

**Comment by isublimity** [comment]
Нзч! Закрою issue -- если не поправил, откройте или новый сделайте )
