### ISSUE TITLE
Can TABIX draw Force-Directed Charts?

### ISSUE THREAD

**Issue by wangzheng0408** [tabixio/tabix#62]
Can TABIX draw graph?
Can TABIX support Echarts Graph?

**Comment by isublimity** [comment]
See docs https://tabix.io/doc/draw/Draw_Chart/

**Comment by wangzheng0408** [comment]
Thank you. I see Tabix can draw Bar,Line,Map and so on.  But i don`t find graph or Force-Directed Charts

**Comment by isublimity** [comment]
Ok, now Tabix not support `graph` chart, no command for draw

I will try to implement soon

https://ecomfe.github.io/echarts-examples/public/editor.html?c=graph-webkit-dep
https://ecomfe.github.io/echarts-examples/public/editor.html?c=graph-circular-layout

**Comment by isublimity** [comment]
Check new build 18.04.1

https://tabix.io/doc/draw/Draw_Graph/

**Comment by wangzheng0408** [comment]
Thank you so much! I have used this function. But i have a question.
Why the graph's edges have no direction arrow?

**Comment by isublimity** [comment]
I add `edgeSymbol:'arrow'`

Try
```
DRAW_GRAPH
{
    path:'country.valueLink.city',
    layout:'force',
    edgeSymbol:['circle', 'arrow']
}

```

https://tabix.io/doc/draw/Draw_Graph/#arrow
