### ISSUE TITLE
Support readonly connection to ClickHouse

### ISSUE THREAD

**Issue by PhantomPhreak** [tabixio/tabix#68]
In current version, tabix requires user account having `readonly=2` mode for connection: https://tabix.io/doc/Requirements/

`readonly=2` setting allowing client to change settings in `system.settings` table, used for applying some restrictions: memory usage, max execution time and so on. Those settings are used for security purposes: https://clickhouse.yandex/docs/ru/single/#_165

So, with current requirements tabix allowing to perform a security violation (by chaning settings), and there is no other way to use tabix interface in a secure way.

Example: i set `max_execution_time=300` for some account to avoid running long lasting/heavy queries. But client can easily change this setting via Tabix interface and overcome this restriction.

Is it possible to support connection for clients having `readonly=1` in profile?
Thanks in advance!

**Comment by Delvish** [comment]
ап теме. автор, возможно ли при использовании readonly=1 использовать tabix? все дело в том, что табиксу не хватает сделать use database, потому как use есть в режимах 0 и 2. может, можно как-то при подключении в той самой строке "Extend params query" указать принудительно базу? ведь cli умеет подключаться при readonly=1

**Comment by loyd** [comment]
Any progress?

**Comment by PhantomPhreak** [comment]
One year passed.

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
