### ISSUE TITLE
Literal sorting in human-readable columns

### ISSUE THREAD

**Issue by leidruid** [tabixio/tabix#69]
Sorting in columns with human-readable values (like memory usage) doesn't use numeric sort
(Screenshot from "Processes" tab)
![default](https://user-images.githubusercontent.com/4631781/40162247-019d1a92-59bc-11e8-95b7-1af67014bd5b.png)

**Comment by isublimity** [comment]
https://handsontable.com/blog/articles/easy-ways-to-sort-different-types-of-data-in-your-app

**Comment by isublimity** [comment]
Public in 18.06.1
