### ISSUE TITLE
Cannot 'open table' shown in section 'Database tree and tables'

### ISSUE THREAD

**Issue by Jack012a** [tabixio/tabix#77]
Tabix.io Build 18.07.1 [20180701]
ClickHouse 18.4.0
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

Based on https://tabix.io/doc/ section Database tree and tables, I would like to open the table structure through the context-menu 'open table'. I have selected the default->ontime table on the left panel, then the page shows a dialog box and asks me 'Do you want to leave this page?'. After I click the OK button, I don't see anything happen.

Browser Console shows the following:

rightMenuProcessTable OpenTables default ontime
<!aceApply in current TAB!>

Question> What is the problem?

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
