### ISSUE TITLE
Where to see the display results from show tables?

### ISSUE THREAD

**Issue by Jack012a** [tabixio/tabix#78]
From console:

:) show tables from system
┌─name───────────────────────────┐
│ aggregate_function_combinators │
...
│ tables                         │
└────────────────────────────────┘
31 rows in set. Elapsed: 0.001 sec.

If I run the same command in Tabix.IO, I only see OK is printed under the Table TAB.

Question> Is there a way that I can see the output results?

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
