### ISSUE TITLE
Ошибка при закрытии вкладок

### ISSUE THREAD

**Issue by Malenkor** [tabixio/tabix#83]
Доброго времени суток! 
При закрытии одной из вкладок с запросом, его текст переносится на следующую вкладку. 
Лечится только перезагрузкой страницы. 

На третьем скрине удален первый запрос, текст которого перешел на второй. После перезагрузки страницы текст второго запроса стал отображаться корректно.

![1](https://user-images.githubusercontent.com/42531989/44323804-f219cb00-a46c-11e8-9b75-6d678896b2d9.jpg)
![2](https://user-images.githubusercontent.com/42531989/44323805-f219cb00-a46c-11e8-8a11-628eee67d979.jpg)
![3](https://user-images.githubusercontent.com/42531989/44323806-f2b26180-a46c-11e8-9620-613561c88860.jpg)

**Comment by isublimity** [comment]
Tabix update to new engine.
Thx you issue.
